function [NEXTUDOTGLOBAL, NEXTUDDOTGLOBAL] = update_implicit(UGLOBAL,...
    PREVUGLOBAL, PREVUDOTGLOBAL, PREVUDDOTGLOBAL, BETA, GAMMA, TIME)
    % Update Acceleration
    NEXTUDDOTGLOBAL = (2/(BETA*TIME^2)).*(UGLOBAL-PREVUGLOBAL) -...
        (2/(BETA*TIME)).*PREVUDOTGLOBAL - ((1-BETA)/BETA).*PREVUDDOTGLOBAL;
    % Update Velocity
    NEXTUDOTGLOBAL = TIME.*((1-GAMMA).*PREVUDDOTGLOBAL + GAMMA.*NEXTUDDOTGLOBAL)...
        + PREVUDOTGLOBAL;
end

